[package]
name = "smithay"
version = "0.2.0"
authors = ["Victor Berger <victor.berger@m4x.org>", "Drakulix (Victor Brekenfeld)"]
license = "MIT"
description = "Smithay is a library for writing wayland compositors."
repository = "https://github.com/Smithay/smithay"
edition = "2018"

[workspace]
members = [ "anvil" ]

[dependencies]
bitflags = "1"
calloop = "0.6.2"
cgmath = "0.18.0"
dbus = { version = "0.9.0", optional = true }
drm-fourcc = "^2.0.0"
drm = { version = "^0.4.0-alpha1", git = "https://github.com/drakulix/drm-rs", branch = "next", optional = true }
gbm = { version = "^0.6.0", git = "https://github.com/drakulix/gbm.rs", branch = "develop", optional = true, default-features = false, features = ["drm-support"] }
image = { version = "0.23.0", optional = true, default-features = false }
input = { version = "0.5", default-features = false, optional = true }
lazy_static = "1"
libc = "0.2.70"
libloading = "0.6.0"
nix = "0.19"
slog = "2"
slog-stdlog = { version = "4", optional = true }
tempfile = { version = "3.0", optional = true }
thiserror = "1"
udev = { version = "0.5", optional = true }
wayland-commons = { version = "0.28", optional = true }
wayland-egl = { version = "0.28", optional = true }
wayland-protocols = { version = "0.28", features = ["unstable_protocols", "server"], optional = true }
wayland-server = { version = "0.28", optional = true }
wayland-sys = { version = "0.28", optional = true }
winit = { version = "0.23.0", optional = true }
xkbcommon = "0.4.0"

[dev-dependencies]
slog-term = "2.3"

[build-dependencies]
gl_generator = { version = "0.14", optional = true }
pkg-config = { version = "0.3.17", optional = true }

[features]
default = ["backend_drm", "backend_gbm", "backend_libinput", "backend_udev", "backend_session_logind", "backend_winit", "renderer_gl", "xwayland", "wayland_frontend", "slog-stdlog"]
backend_winit = ["winit", "wayland-server/dlopen", "backend_egl", "wayland-egl", "renderer_gl", "use_system_lib"]
backend_drm = ["drm"]
backend_gbm = ["gbm"]
backend_egl = ["gl_generator"]
backend_libinput = ["input"]
backend_session = []
backend_udev = ["udev"]
backend_session_logind = ["dbus", "backend_session", "pkg-config"]
backend_session_elogind = ["backend_session_logind"]
renderer_gl = ["gl_generator", "backend_egl"]
use_system_lib = ["wayland_frontend", "wayland-sys", "wayland-server/use_system_lib"]
wayland_frontend = ["wayland-server", "wayland-commons", "wayland-protocols", "tempfile"]
xwayland = ["wayland_frontend"]
test_all_features = ["default"]

[[example]]
name = "raw_legacy_drm"
required-features = ["backend_drm"]

[[example]]
name = "raw_atomic_drm"
required-features = ["backend_drm"]
